before_build:
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

build_script:
  - ps: .\build.ps1 -Target CI -verbosity Verbose -configuration Release

artifacts:
  - path: 'nugets\*.nupkg'

cache:
  - packages -> paket.lock

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: master
      appveyor_repo_tag: true
